const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");

const MODULES = [
  ["./main", "main.js"],
  ["./src/sessionRegistry", "src/sessionRegistry.js"],
  ["./src/providers", "src/providers.js"],
  ["./src/bridgeClient", "src/bridgeClient.js"],
  ["./src/bridgeSetup", "src/bridgeSetup.js"],
  ["./src/turnTransport", "src/turnTransport.js"],
  ["./src/sessionExport", "src/sessionExport.js"],
  ["./src/providerStatus", "src/providerStatus.js"],
  ["./src/writebackTargets", "src/writebackTargets.js"],
  ["./src/writeback", "src/writeback.js"],
  ["./src/agentStatusBridge", "src/agentStatusBridge.js"],
  ["./src/workflowConfig", "src/workflowConfig.js"],
  ["./src/promptCompiler", "src/promptCompiler.js"],
];

function readModule(relativePath) {
  const absolutePath = path.join(ROOT, relativePath);
  return fs.readFileSync(absolutePath, "utf8").replace(/\brequire\s*\(/g, "__agentChatLocalRequire(");
}

function renderBundle() {
  const moduleEntries = MODULES.map(([id, relativePath]) => {
    const source = readModule(relativePath);
    return `${JSON.stringify(id)}: function(__agentChatLocalRequire, module, exports) {\n${source}\n}`;
  }).join(",\n");

  return `/* Generated by scripts/build.js. Do not edit dist/main.js directly. */\n` +
`const __agentChatModules = {\n${moduleEntries}\n};\n` +
`const __agentChatCache = {};\n` +
`function __agentChatNormalize(parentId, requestedId) {\n` +
`  if (!requestedId.startsWith(".")) {\n` +
`    return requestedId;\n` +
`  }\n` +
`  const parentParts = parentId.split("/");\n` +
`  parentParts.pop();\n` +
`  for (const part of requestedId.split("/")) {\n` +
`    if (!part || part === ".") continue;\n` +
`    if (part === "..") parentParts.pop();\n` +
`    else parentParts.push(part);\n` +
`  }\n` +
`  let normalized = parentParts.join("/");\n` +
`  if (!normalized.startsWith(".")) normalized = "./" + normalized;\n` +
`  return normalized.replace(/\\.js$/, "");\n` +
`}\n` +
`function __agentChatRequire(parentId, requestedId) {\n` +
`  const resolvedId = __agentChatNormalize(parentId, requestedId);\n` +
`  if (!__agentChatModules[resolvedId]) {\n` +
`    return require(requestedId);\n` +
`  }\n` +
`  if (__agentChatCache[resolvedId]) {\n` +
`    return __agentChatCache[resolvedId].exports;\n` +
`  }\n` +
`  const module = { exports: {} };\n` +
`  __agentChatCache[resolvedId] = module;\n` +
`  __agentChatModules[resolvedId]((id) => __agentChatRequire(resolvedId, id), module, module.exports);\n` +
`  return module.exports;\n` +
`}\n` +
`module.exports = __agentChatRequire(".", "./main");\n`;
}

function copyReleaseFile(fileName) {
  fs.copyFileSync(path.join(ROOT, fileName), path.join(DIST, fileName));
}

function build() {
  fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(path.join(DIST, "main.js"), renderBundle(), "utf8");
  copyReleaseFile("manifest.json");
  copyReleaseFile("styles.css");
}

build();
